Fix k8s provision (#366)
* Fix NUM_SECONDARY_NICS default value

Wrong default value syntax was used for NUM_SECONDARY_NICS

Signed-off-by: Or Shoval <oshoval@redhat.com>

* Fix for docker daemon error during provisioning k8s-1.17

docker-ce 19.03.9 cause
ERROR: Error response from daemon: client version 1.40 is too new.
Maximum supported API version is 1.39

One of the possible recommended ways is using API 1.39.

See
https://github.com/kubernetes-sigs/kubespray/issues/6160

Signed-off-by: Or Shoval <oshoval@redhat.com>

* Fix support of secondary interfaces, K8s-1.17

NetworkManager-wait-online.service is causing the boot to take
much longer when secondary interfaces exists,
as a result, check-up during provision and cluster-up
would fail connecting to the node as long as the boot isnt finished.
By installing NetworkManager-config-server,
existing network profiles wont be changed, and the boot wont
be stalled by NetworkManager-wait-online.service.

Signed-off-by: Or Shoval <oshoval@redhat.com>

* Update K8s-1.17 hash

Signed-off-by: Or Shoval <oshoval@redhat.com>