Add centos9 image build to publish.sh
The image is required to be built locally when publishing the 1.26
provider, which is the first to use it.

Error: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1595821136107540480#1:build-log.txt%3A26814

Signed-off-by: Daniel Hiller <dhiller@redhat.com>