Fix for docker daemon error during provisioning k8s-1.17
docker-ce 19.03.9 cause
ERROR: Error response from daemon: client version 1.40 is too new.
Maximum supported API version is 1.39

One of the possible recommended ways is using API 1.39.

See
https://github.com/kubernetes-sigs/kubespray/issues/6160

Signed-off-by: Or Shoval <oshoval@redhat.com>